linters:
  Comment:
    enabled: false

  LeadingZero:
    enabled: false

  MergeableSelector:
    force_nesting: false

  PropertySortOrder:
    enabled: true,
    order: recess

  SelectorDepth:
    enabled: false

  TrailingWhitespace:
    enabled: false
